image: fedora/32
packages:
  - npm
  - rsync
sources:
  - https://github.com/sauerbraten/bot.git
environment:
  DEPLOY: p1x.pw
secrets:
  - 956ddc04-c911-4147-bc90-30bb08276c3e # ci@ng.p1x.pw ssh key
  - 0eb47a86-d098-4756-8fc1-5c570eee8fb8 # discord bot token
tasks:
  - version: |
      cd bot
      sed -i "s/<<hash>>/$(git rev-parse --short HEAD)/" novibot.js
      sed -i "s/<<author>>/$(git show -s --format=%an)/" novibot.js
      sed -i "s/<<subject>>/$(git show -s --format=%s)/" novibot.js
  - dependencies: |
      cd bot
      npm install
  - deploy: |
      cd bot
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq node_modules ~/.discord_token novibot.js ci@$DEPLOY:~/bot/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'killall node || true'
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd bot; export DISCORD_TOKEN=$(cat  .discord_token); nohup node novibot.js >> log.txt 2>&1 &'
