image: alpine/edge
packages:
  - npm
  - rsync
sources:
  - https://git.sr.ht/~sauerbraten/jarvis
environment:
  DEPLOY: chef.sauerworld.org
secrets:
  - 98c1b481-b37f-452f-872a-8f8fa1833249
  - 0eb47a86-d098-4756-8fc1-5c570eee8fb8
tasks:
  - version: |
      cd jarvis
      sed -i "s/<filled in by CI service>/$(git rev-parse --short HEAD)/" novibot.js
  - dependencies: |
      cd jarvis
      npm install
  - deploy: |
      cd jarvis
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq node_modules ~/.discord_token novibot.js ci@$DEPLOY:~/bot/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'killall nodejs'
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd bot; export DISCORD_TOKEN=$(cat  .discord_token); nohup nodejs novibot.js &>> log.txt &'
